[build]
  command = "npm run build"
  publish = "dist"

# Optional: Specify your functions folder (if using Netlify Functions)
# functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
